version: '3.8'

services:
  react:
    image: phonebook-frontend
    build:
      context: ./phonebook-frontend
      dockerfile: Dockerfile
    container_name: phonebook-frontend
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./phonebook-backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./phonebook-backend/mongo_data:/data/db
    container_name: mongo
  express:
    image: phonebook-backend
    build:
      context: ./phonebook-backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database
    container_name: phonebook-backend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 3000:80
    container_name: reverse-proxy
    depends_on:
      - react
      - express
